### ISSUE TITLE
Support for multiple AS5600 Hall sensors

### ISSUE THREAD

**Issue by GioCC** [FreeJoy-Team/FreeJoy#35]
Just a suggestion.
As you will probably agree, the single-address design of AS5600 Hall sensors was not the greatest idea by its manufacturer, but that's something we have to live with.
Since it's almost a shame to have the support for that component available in FreeJoy, but with very limited utility given that constraint, do you think it would be possible to add support for an I2C multiplexer like the TCA9548? This would allow to have up to 8 sensors, which would be enough for a complete set of axes.
(Don't know but it might become handy for some other of the I2C peripherals too).
Thanks for your EXCELLENT job!

**Comment by vostrenkov** [comment]
Hello, 
I2C is a quite slow part of the code and using multiple I2C devices may significantly reduce overall performance (i had some problems with using DMA for I2C).
I added AD5600 sensors just because it was quite easy and i had them in stock, but i'd recommend to use SPI sensors like TLE5011 instead of I2C periphery. 
Another option is to add support for other AMS sensor AS5048 but i don't like its price
