### ISSUE TITLE
hx711

### ISSUE THREAD

**Issue by M0rta** [FreeJoy-Team/FreeJoy#61]
Hi!
Support load cells?

**Comment by vostrenkov** [comment]
Hi,
You can connect load cells to analog input through the amplifier

**Comment by M0rta** [comment]
ok! great, but need to use 2 analog inputs?
the arduino way looks like this:

#define LOADCELL_DOUT_PIN A0
#define LOADCELL_SCK_PIN A1

same way in freejoy?
tnx!

**Comment by vostrenkov** [comment]
Please take a look to our wiki page. In FreeJoy you do everything through configurator utility

**Comment by M0rta** [comment]
ok, believe me I'm looking for what I need but I can't find how to connect it, and that's why I'm asking this way.
my doubts are that in arduino, I connect + | - | and 2 pins, since there are 4 cables and only 3 in an analog.
I go back to check the wiki, but if you can please give me some help, I really appreciate it.

**Comment by vostrenkov** [comment]
Since you have SCK and DOUT pins for Arduino you use not analog but digital interface. I guess it is hx711 IC that amplify analog signal from load cell and covert it into digital format.
FreeJoy doesn't support HX711's digital interface so if you want to use load cells with it you should use analog signal (on pins A0-A7). Raw analog signal from load cell is quite small and you will have to use amplifier (like AD623) between load cell and bluepill analog pin

**Comment by vostrenkov** [comment]
All analog sensors are pretty the same for freejoy so amplifier output connects to analog pin just like pot or hall sensor

**Comment by M0rta** [comment]
I understand perfectly now.
it was never going to work for compatibility reasons.
Without support for hx711, I will not be able to connect the load cell, if I want to use freejoy.
Thank you very much for your work and your time.

**Comment by vorrin** [comment]
Hello! 
Are there any plans for this to ever be implemented? 
Is it something that could be added in a pull request? It looks like bluepill itself can run one fine enough with a small quantity of implementation (as per https://www.micropeta.com/video108) would there maybe be some documentation to get one's bearing in how to implement it directly? Thanks!
